version: '3.9'
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all    
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama    

volumes:
  ollama: